project:
  type: website
  output-dir: docs

website:
  title: "William 'Billy' Johnson"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: Environmental Data Science Applications Water Resources
        href: Projects.qmd
      - text: Snow Hydrology
        menu:
          - text: Overview
            href: snow_hydro.qmd
          - text: Geospatial
            href: Geospatial.qmd
          - text: Cloud Cover and Precipitation
            href: CloudCover.qmd
          - text: Trace Events, Precipitation Under Catch and Probability of Snow
            href: Trace.qmd
          - text: Accumulation, Fresh Snow and Albedo
            href: Accumulation.qmd
          - text: Canopy Interception
            href: Canopy.qmd
          - text: Densification & Metamorphism
            href: metemorphism.qmd
          - text: Redistribution
            href: redistribution.qmd

format:
  html:
    theme: Superhero
    css: styles.css
    toc: true

editor: visual

